Support constant evaluation for `#if` and `#elif` preprocessor directive
sysprog21/shecc pull request #111
Opened 2024-02-23 00:18 UTC by ChAoSUnItY

- Implement constant evaluation for `#if` and `#ifdef` preprocessor directive
  - Notice that short-circuit is not yet implemented.

2024-02-23 00:35 UTC, ChAoSUnItY commented
This Pull Request will be ready for review once after #111 is merged.

2024-02-23 10:27 UTC, jserv requested changes
Rebase the latest `master` branch.

2024-02-24 15:04 UTC, jserv commented
I defer to @vacantron for confirmation.

2024-02-24 15:12 UTC, vacantron approved these changes

2024-02-24 15:34 UTC, merged

2024-02-24 15:34 UTC, jserv commented
Thank @ChAoSUnItY for contributing!