Support variable declaration in for loop setup
sysprog21/shecc pull request #117
Opened 2024-03-04 03:07 UTC by ChAoSUnItY

- Resolve #115 , this allows variables declare in the scope of for loop body, to avoid loose variable liveness, in other word, variable can have stricter scope liveness by declaring in setup section of for loop.

2024-03-04 03:31 UTC, jserv commented
CI complains below:
```
tests/check-snapshots.sh
Files /dev/fd/63 and /dev/fd/62 differ
Error: writing output failed: Broken pipe
cat: write error: Broken pipe
Files /dev/fd/63 and /dev/fd/62 differ
```

@vacantron, can you help resolve?

2024-03-04 03:36 UTC, jserv commented on tests/driver.sh
> +# for-loop var decl
Change the comment to "Variables can be declared within a for-loop iteration"

2024-03-04 10:38 UTC, vacantron requested changes

2024-03-04 10:38 UTC, vacantron commented on src/parser.c
> +                var = require_var(parent);
The scope of the declaration in the first clause should be different from the others that outside of the for-statement. i.e. you need to create another scope with `read_code_block()` or something else first.

2024-03-04 10:52 UTC, vacantron commented
> CI complains below:
> 
> ```
> tests/check-snapshots.sh
> Files /dev/fd/63 and /dev/fd/62 differ
> Error: writing output failed: Broken pipe
> cat: write error: Broken pipe
> Files /dev/fd/63 and /dev/fd/62 differ
> ```
> 
> @vacantron, can you help resolve?

The new cfront feature is going to change the CFGs. Use `tests/update-snapshots.sh` to update the outdated ones.

By the way, the changes causes the unexpected behavior while unwinding the phi instruction in the second stage, and breaks the self-hosting. I'm trying to figure it out.

2024-03-17 17:02 UTC, vacantron commented
Rebase the `master` branch after #113 being merged, and the error should be solved.

2024-03-18 02:56 UTC, ChAoSUnItY commented
That's weird, I updated snapshot after rebase and it still panics on stage 2.

2024-03-18 16:24 UTC, vacantron commented
> That's weird, I updated snapshot after rebase and it still panics on stage 2.

The second stage is broken by the SSA now, but the snapshot test should be passed tho.

I run `head -c20 tests/snapshots/xxx.json | tail -c19` for the `hello` and `fib`, and both of them has 469 basic blocks. It is definitely incorrect. The `fib` one should have ten more than the `hello`. Can you try it again with `make disclean` and `make config ARCH=arm` ?

2024-03-18 18:20 UTC, ChAoSUnItY commented
> Can you try it again with `make disclean` and `make config ARCH=arm` ?

After running `disclean` and `config ARCH=arm`, now running `tests/update-snapshots.sh` would stuck forever (I terminted it after running for 2.6 mins). Can you confirm this weird behavior?

2024-03-19 01:55 UTC, vacantron commented
> After running `disclean` and `config ARCH=arm`, now running `tests/update-snapshots.sh` would stuck forever (I terminted it after running for 2.6 mins). Can you confirm this weird behavior?

There is a typo in the commands that I provided previously. Try `make distclean config ARCH=riscv out/shecc-stage1.elf` and `tests/update-snapshots.sh` again. Do you run them on Linux?

2024-03-19 04:50 UTC, ChAoSUnItY commented
> Do you run them on Linux?
Yes, specifically, on Arch Linux.

> Try make distclean config ARCH=riscv out/shecc-stage1.elf and tests/update-snapshots.sh again.
It still failed on stage 2.

2024-03-19 06:58 UTC, vacantron commented
> Yes, specifically, on Arch Linux.

Can you test the `jq` command with `-S` option separately on your machine? The result seems not to be sorted in ascending order by the `_gvid`.

2024-03-19 07:33 UTC, ChAoSUnItY commented
I can confirm that using `jq -S -c . hello.json > hello.json` (from `tests/update-snapshot.sh`) does only sorted by json keys but `_gvid` value.

2024-03-19 16:26 UTC, jserv requested changes
Rebase the latest `master` branch and re-generate snapshots.

2024-03-20 20:01 UTC, jserv commented
> Leave a blank line between the subject and the body of the commit message, and use `git rebase -i` to squash some commits

See also: https://cbea.ms/git-commit/

2024-03-21 08:46 UTC, vacantron approved these changes

2024-03-21 08:59 UTC, merged

2024-03-21 08:59 UTC, jserv commented
Thank @ChAoSUnItY for contributing!