Implement #undef preprocessor derictive
sysprog21/shecc pull request #74
Opened 2023-08-12 17:29 UTC by ChAoSUnItY

Implements `#undef` preprocessor derictive. 

One concern in current approach is that due to the memory allocations of `alias_t *ALIASES` and `macro_t *MACROS`, the removal operation's time complexity is `O(N)`, this might causes some performance overhead in future development.

2023-08-12 17:54 UTC, jserv commented on .gitignore
> +# Vscode
Don't do this! Minimize the necessary changes.

2023-08-12 17:55 UTC, jserv commented on src/globals.c
> +char *find_alias(char *alias)
Don't do this. Minimize the necessary changes.

2023-08-13 05:40 UTC, ChinYikMing commented
Maybe You can introduce a `disabled` variable in `alias_t` structure. If the variable is set then it cannot be used otherwise it can. This can improve performance from O(n) to O(1). So, `remove_alias` can be simplified to set the `disabled` variable instead. In addition, you may need to modify the `find_alias` function to consider the `disabled` variable.

But, I think #undef is not used so that much for now, so moving around the element when calling `remove_alias` is acceptable.

2023-08-14 06:26 UTC, ChAoSUnItY commented
I see. Should I open another issue for this suggestion?

2023-08-14 06:41 UTC, jserv commented
> I see. Should I open another issue for this suggestion?

Simply rework the commits for preprocessor specific changes.

2023-08-14 07:38 UTC, jserv requested changes
Squash the commits and improve git commit message.

2023-08-14 08:47 UTC, merged